Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
Посещена главная страница. IP: 127.0.0.1, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
"GET / HTTP/1.1" 200 344
Посещена главная страница. IP: 127.0.0.1, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
"GET / HTTP/1.1" 200 344
"GET /about HTTP/1.1" 301 0
Посещена страница 'О себе'. IP: 127.0.0.1, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
"GET /about/ HTTP/1.1" 200 320
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
VISIT MAIN PAGE IP: 127.0.0.1, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
"GET / HTTP/1.1" 200 206
VISIT ABOUT PAGE 'О себе'. IP: 127.0.0.1, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
"GET /about/ HTTP/1.1" 200 194
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 10629
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2111
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 3263
"GET /create_client/ HTTP/1.1" 200 1268
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /create_client/ HTTP/1.1" 200 1092
"POST /create_client/ HTTP/1.1" 200 1249
"POST /create_client/ HTTP/1.1" 200 1249
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /create_client/
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: apphw_client

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 29, in create_client
    form.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 552, in save
    self.instance.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: apphw_client
"POST /create_client/ HTTP/1.1" 500 153758
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 3263
"GET /create_client/ HTTP/1.1" 200 1115
Internal Server Error: /create_client/
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: apphw_client

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 29, in create_client
    form.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 552, in save
    self.instance.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: apphw_client
"POST /create_client/ HTTP/1.1" 500 155268
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 3263
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3314
"GET /create_client/ HTTP/1.1" 200 1115
Internal Server Error: /create_client/
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 29, in create_client
    form.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 552, in save
    self.instance.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date
"POST /create_client/ HTTP/1.1" 500 155322
"GET /create_client/ HTTP/1.1" 200 1115
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /create_client/
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 29, in create_client
    form.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 552, in save
    self.instance.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date
"POST /create_client/ HTTP/1.1" 500 155550
"GET /create_client/ HTTP/1.1" 200 1115
Internal Server Error: /create_client/
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 29, in create_client
    form.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 552, in save
    self.instance.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date
"POST /create_client/ HTTP/1.1" 500 155486
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /create_client/10
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 31, in create_client
    return render(request, 'create_client.html', {'count': count})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 475, in parse
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Empty variable tag on line 10
"GET /create_client/10 HTTP/1.1" 500 125168
"GET /create_client/10 HTTP/1.1" 200 271
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /create_client/10 HTTP/1.1" 200 271
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /create_client/10
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 32, in create_client
    client.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date
"GET /create_client/10 HTTP/1.1" 500 154365
Internal Server Error: /create_client/10
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 32, in create_client
    client.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date
"GET /create_client/10 HTTP/1.1" 500 154110
Internal Server Error: /create_client/10
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 32, in create_client
    client.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date
"GET /create_client/10 HTTP/1.1" 500 154263
Not Found: /
"GET / HTTP/1.1" 404 3280
Not Found: /create_client/
"GET /create_client/ HTTP/1.1" 404 3340
Not Found: /create_client/
"GET /create_client/ HTTP/1.1" 404 3340
Internal Server Error: /create_client/2
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 32, in create_client
    client.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date
"GET /create_client/2 HTTP/1.1" 500 153944
Watching for file changes with StatReloader
Internal Server Error: /create_client/2
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 32, in create_client
    client.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: apphw_client.registration_date
"GET /create_client/2 HTTP/1.1" 500 154302
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /create_client/2 HTTP/1.1" 200 270
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 52, in client_list
    return render(request, 'client_list.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_client' with no arguments not found. 1 pattern(s) tried: ['create_client/(?P<count>[0-9]+)\\Z']
"GET / HTTP/1.1" 500 128303
"GET / HTTP/1.1" 200 1966
"GET /create_client/1 HTTP/1.1" 200 270
"GET / HTTP/1.1" 200 2517
"GET /delete_client/2/ HTTP/1.1" 200 703
"POST /delete_client/2/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 1873
"GET /delete_client/1/ HTTP/1.1" 200 703
"POST /delete_client/1/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 1242
"GET / HTTP/1.1" 200 1289
"GET /view_client/3/ HTTP/1.1" 200 740
"GET /update_client/3/ HTTP/1.1" 200 1242
"GET /create_client/1 HTTP/1.1" 200 270
"GET /create_client/1 HTTP/1.1" 200 270
Not Found: /create_client/
"GET /create_client/ HTTP/1.1" 404 3328
"GET /create_client/50 HTTP/1.1" 200 271
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 32566
"GET /view_client/51/ HTTP/1.1" 200 740
"GET /delete_client/25/ HTTP/1.1" 200 602
"GET / HTTP/1.1" 200 32566
"GET /view_client/14/ HTTP/1.1" 200 730
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 32566
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 84, in input_image
    return render(request, '',{})
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\base.py", line 23, in get_template
    contents = self.get_contents(origin)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\cached.py", line 26, in get_contents
    return origin.loader.get_contents(origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\filesystem.py", line 22, in get_contents
    with open(origin.name, encoding=self.engine.file_charset) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\Desktop\\Django\\django_venv\\Lib\\site-packages\\django\\contrib\\admin\\templates'
"GET /input_image HTTP/1.1" 500 112911
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 32566
"GET /input_image HTTP/1.1" 200 597
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 32566
"GET /input_image HTTP/1.1" 200 534
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 80, in input_image
    form = ImageForm()
           ^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"POST /input_image HTTP/1.1" 500 74594
"GET /input_image HTTP/1.1" 200 528
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 80, in input_image
    form = ImageForm()
           ^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"POST /input_image HTTP/1.1" 500 74594
"GET /input_image HTTP/1.1" 200 528
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 80, in input_image
    form = ImageForm()
           ^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"POST /input_image HTTP/1.1" 500 74594
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 84, in input_image
    form = ImageForm()
           ^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /input_image HTTP/1.1" 500 73491
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 84, in input_image
    form = ImageForm()
           ^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /input_image HTTP/1.1" 500 73491
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 84, in input_image
    form = ImageForm()
           ^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /input_image HTTP/1.1" 500 73491
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /input_image HTTP/1.1" 200 1275
"POST /input_image HTTP/1.1" 200 1275
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 1275
"GET /input_image HTTP/1.1" 200 1275
"POST /input_image HTTP/1.1" 200 1275
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /input_image HTTP/1.1" 200 1263
"POST /input_image HTTP/1.1" 200 1263
"GET / HTTP/1.1" 200 691
"GET /create_client/1 HTTP/1.1" 200 270
"GET / HTTP/1.1" 200 1296
"GET /create_client/1 HTTP/1.1" 200 270
"GET /create_client/10 HTTP/1.1" 200 271
"GET / HTTP/1.1" 200 7844
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7844
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 91, in input_image
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /input_image HTTP/1.1" 500 73523
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 91, in input_image
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /input_image HTTP/1.1" 500 73660
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 91, in input_image
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /input_image HTTP/1.1" 500 73660
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 91, in input_image
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /input_image HTTP/1.1" 500 73660
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 91, in input_image
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /input_image HTTP/1.1" 500 73664
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7844
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 91, in input_image
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /input_image HTTP/1.1" 500 73527
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 1263
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 1263
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7844
"GET /input_image HTTP/1.1" 200 1097
"POST /input_image HTTP/1.1" 200 1097
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /input_image HTTP/1.1" 200 1097
"GET /input_image HTTP/1.1" 200 1097
"GET /input_image HTTP/1.1" 200 1097
"GET /input_image HTTP/1.1" 200 1097
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /input_image HTTP/1.1" 200 1097
"GET /input_image HTTP/1.1" 200 1097
"GET /input_image HTTP/1.1" 200 1097
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /input_image HTTP/1.1" 200 1097
"GET /input_image HTTP/1.1" 200 1097
"GET /input_image HTTP/1.1" 200 1097
"GET /input_image HTTP/1.1" 200 1097
"GET /input_image HTTP/1.1" 200 1097
Watching for file changes with StatReloader
"GET /input_image HTTP/1.1" 200 1097
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /input_image HTTP/1.1" 200 1264
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /input_image HTTP/1.1" 200 1249
"POST /input_image HTTP/1.1" 200 1249
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 1249
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 1272
"POST /input_image HTTP/1.1" 200 1272
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 1407
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 1407
"POST /input_image HTTP/1.1" 200 1408
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 1408
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 1627
"POST /input_image HTTP/1.1" 200 1642
"POST /input_image HTTP/1.1" 200 1641
"POST /input_image HTTP/1.1" 200 1641
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7844
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3497
"GET /input_image HTTP/1.1" 200 1412
"POST /input_image HTTP/1.1" 200 1640
"POST /input_image HTTP/1.1" 200 1639
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\HW_proj\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\HW_proj\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7844
"GET /input_image HTTP/1.1" 200 666
"POST /input_image HTTP/1.1" 200 748
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 748
"POST /input_image HTTP/1.1" 200 748
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 748
"POST /input_image HTTP/1.1" 200 748
"POST /input_image HTTP/1.1" 200 748
"POST /input_image HTTP/1.1" 200 780
"POST /input_image HTTP/1.1" 200 698
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /input_image HTTP/1.1" 200 1842
"POST /input_image HTTP/1.1" 200 1594
"POST /input_image HTTP/1.1" 200 1593
"POST /input_image HTTP/1.1" 200 1593
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7844
"GET /input_image HTTP/1.1" 200 1444
"POST /input_image HTTP/1.1" 200 1592
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7844
"GET /input_image HTTP/1.1" 200 1304
"POST /input_image HTTP/1.1" 200 1352
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7844
"GET /input_image HTTP/1.1" 200 1304
Internal Server Error: /input_image
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: table apphw_product has no column named image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 89, in input_image
    product.save()
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table apphw_product has no column named image
"POST /input_image HTTP/1.1" 500 154409
Watching for file changes with StatReloader
"GET /input_image HTTP/1.1" 200 1304
"POST /input_image HTTP/1.1" 200 1352
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 691
Not Found: /input_image
"GET /input_image HTTP/1.1" 404 3679
Not Found: /create_client/
"GET /create_client/ HTTP/1.1" 404 3688
"GET /create_client/10 HTTP/1.1" 200 271
"GET / HTTP/1.1" 200 6690
Not Found: /input_image
"GET /input_image HTTP/1.1" 404 3679
Not Found: /add_product/
"GET /add_product/ HTTP/1.1" 404 3682
Not Found: /add_product/
"GET /add_product/ HTTP/1.1" 404 3682
"GET /add_product HTTP/1.1" 200 1304
"POST /add_product HTTP/1.1" 200 1371
Not Found: /productы_дшые
"GET /product%D1%8B_%D0%B4%D1%88%D1%8B%D0%B5 HTTP/1.1" 404 3720
"GET /products_list HTTP/1.1" 200 627
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /products_list HTTP/1.1" 200 1106
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /products_list HTTP/1.1" 200 1158
"GET /products_list HTTP/1.1" 200 1262
"GET / HTTP/1.1" 200 6690
Not Found: /input_image
"GET /input_image HTTP/1.1" 404 3679
Not Found: /wqeqwe
"GET /wqeqwe HTTP/1.1" 404 3664
Internal Server Error: /products_list
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 85, in products_list
    return render(request, 'products_list.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 1380, in url
    viewname = parser.compile_filter(bits[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{product.image}}' from '{{product.image}}'
"GET /products_list HTTP/1.1" 500 165382
Internal Server Error: /products_list
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 85, in products_list
    return render(request, 'products_list.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '{{product.image}}' not found. '{{product.image}}' is not a valid view function or pattern name.
"GET /products_list HTTP/1.1" 500 132546
Internal Server Error: /products_list
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 85, in products_list
    return render(request, 'products_list.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 1380, in url
    viewname = parser.compile_filter(bits[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''{product.image}'' from 'f'{product.image}''
"GET /products_list HTTP/1.1" 500 166472
Internal Server Error: /products_list
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 85, in products_list
    return render(request, 'products_list.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '{product.image}' not found. '{product.image}' is not a valid view function or pattern name.
"GET /products_list HTTP/1.1" 500 132498
Internal Server Error: /products_list
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 85, in products_list
    return render(request, 'products_list.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'product.image' not found. 'product.image' is not a valid view function or pattern name.
"GET /products_list HTTP/1.1" 500 132450
Internal Server Error: /products_list
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 85, in products_list
    return render(request, 'products_list.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'product.image' not found. 'product.image' is not a valid view function or pattern name.
"GET /products_list HTTP/1.1" 500 132450
Internal Server Error: /products_list
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 85, in products_list
    return render(request, 'products_list.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'product.image' not found. 'product.image' is not a valid view function or pattern name.
"GET /products_list HTTP/1.1" 500 132450
"GET /products_list HTTP/1.1" 200 1376
Not Found: /firefox_vasII0btnq.png
"GET /firefox_vasII0btnq.png HTTP/1.1" 404 3712
Not Found: /firefox_vasII0btnq.png
"GET /firefox_vasII0btnq.png HTTP/1.1" 404 3712
"GET /products_list HTTP/1.1" 200 1372
"GET /products_list HTTP/1.1" 200 1372
Not Found: /firefox_vasII0btnq.png
"GET /firefox_vasII0btnq.png HTTP/1.1" 404 3712
Not Found: /media/j1VJO1GENf.png
"GET /media/j1VJO1GENf.png HTTP/1.1" 404 3706
"GET /products_list HTTP/1.1" 200 1262
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6690
Not Found: /input_image
"GET /input_image HTTP/1.1" 404 3679
"GET /products_list HTTP/1.1" 200 1326
"GET /products_list HTTP/1.1" 200 1354
"GET /products_list HTTP/1.1" 200 1354
"GET /products_list HTTP/1.1" 200 1354
"GET /products_list HTTP/1.1" 200 1354
"GET /products_list HTTP/1.1" 200 1354
"GET /products_list HTTP/1.1" 200 1344
"GET /products_list HTTP/1.1" 200 1390
Watching for file changes with StatReloader
"GET /products_list HTTP/1.1" 200 1390
Watching for file changes with StatReloader
"GET /products_list HTTP/1.1" 200 1670
Watching for file changes with StatReloader
"GET /products_list HTTP/1.1" 200 1586
Not Found: /.../media/firefox_AFUCwJooyU.png
"GET /.../media/firefox_AFUCwJooyU.png HTTP/1.1" 404 3742
"GET /products_list HTTP/1.1" 200 1592
Not Found: /apphw/media/firefox_AFUCwJooyU.png
"GET /apphw/media/firefox_AFUCwJooyU.png HTTP/1.1" 404 3748
"GET /products_list HTTP/1.1" 200 1592
Not Found: /apphw/media/firefox_AFUCwJooyU.png
"GET /apphw/media/firefox_AFUCwJooyU.png HTTP/1.1" 404 3748
"GET /products_list HTTP/1.1" 200 1592
Not Found: /apphw/media/firefox_AFUCwJooyU.png
"GET /apphw/media/firefox_AFUCwJooyU.png HTTP/1.1" 404 3748
"GET /products_list HTTP/1.1" 200 1592
Not Found: /apphw/media/firefox_AFUCwJooyU.png
"GET /apphw/media/firefox_AFUCwJooyU.png HTTP/1.1" 404 3748
"GET /products_list HTTP/1.1" 200 1592
Not Found: /apphw/media/firefox_AFUCwJooyU.png
"GET /apphw/media/firefox_AFUCwJooyU.png HTTP/1.1" 404 3748
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6690
"GET /products_list HTTP/1.1" 200 1686
"GET /products_list HTTP/1.1" 200 1686
"GET /products_list HTTP/1.1" 200 1686
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6690
Internal Server Error: /products_list
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\HW\HW_proj\apphw\views.py", line 85, in products_list
    return render(request, 'products_list.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':///C:/Users/user/Desktop/Django/HW/HW_proj/apphw/media/{{ product.image' from 'file:///C:/Users/user/Desktop/Django/HW/HW_proj/apphw/media/{{ product.image'
"GET /products_list HTTP/1.1" 500 163070
"GET /products_list HTTP/1.1" 200 1686
"GET / HTTP/1.1" 200 6690
"GET /products_list HTTP/1.1" 200 1610
Not Found: /firefox_vasII0btnq.png
Not Found: /media/j1VJO1GENf.png
"GET /media/j1VJO1GENf.png HTTP/1.1" 404 3706
"GET /firefox_vasII0btnq.png HTTP/1.1" 404 3712
"GET /products_list HTTP/1.1" 200 1686
"GET /products_list HTTP/1.1" 200 1686
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
Watching for file changes with StatReloader
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1566
Not Found: /firefox_AFUCwJooyU.png
"GET /firefox_AFUCwJooyU.png HTTP/1.1" 404 3712
"GET /products_list HTTP/1.1" 200 1566
Not Found: /firefox_AFUCwJooyU.png
"GET /firefox_AFUCwJooyU.png HTTP/1.1" 404 3712
"GET /products_list HTTP/1.1" 200 1566
Not Found: /firefox_AFUCwJooyU.png
"GET /firefox_AFUCwJooyU.png HTTP/1.1" 404 3712
"GET /products_list HTTP/1.1" 200 1566
Not Found: /firefox_AFUCwJooyU.png
"GET /firefox_AFUCwJooyU.png HTTP/1.1" 404 3712
"GET /products_list HTTP/1.1" 200 1566
Not Found: /firefox_AFUCwJooyU.png
"GET /firefox_AFUCwJooyU.png HTTP/1.1" 404 3712
"GET /products_list HTTP/1.1" 200 1568
Not Found: /.firefox_AFUCwJooyU.png
"GET /.firefox_AFUCwJooyU.png HTTP/1.1" 404 3715
"GET /products_list HTTP/1.1" 200 1568
Not Found: /.firefox_AFUCwJooyU.png
"GET /.firefox_AFUCwJooyU.png HTTP/1.1" 404 3715
"GET /products_list HTTP/1.1" 200 1568
Not Found: /.firefox_AFUCwJooyU.png
"GET /.firefox_AFUCwJooyU.png HTTP/1.1" 404 3715
"GET /products_list HTTP/1.1" 200 1572
Not Found: /...firefox_AFUCwJooyU.png
"GET /...firefox_AFUCwJooyU.png HTTP/1.1" 404 3721
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
Watching for file changes with StatReloader
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
"GET /products_list HTTP/1.1" 200 1674
C:\Users\user\Desktop\Django\HW\HW_proj\HW_proj\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"GET /static/admin/css/base.css HTTP/1.1" 200 21544
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4626
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5944
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /admin/auth/user/ HTTP/1.1" 200 11916
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/actions.js HTTP/1.1" 200 8067
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /admin/auth/group/ HTTP/1.1" 200 7783
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/add/ HTTP/1.1" 200 12862
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15492
"GET /static/admin/css/forms.css HTTP/1.1" 200 9090
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"GET /admin/ HTTP/1.1" 200 5944
"GET /admin/auth/user/ HTTP/1.1" 200 11916
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/ HTTP/1.1" 200 5944
"GET /admin/auth/user/ HTTP/1.1" 200 11916
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/user/?_facets=True HTTP/1.1" 200 12323
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/img/icon-hidelink.svg HTTP/1.1" 200 784
"GET /admin/auth/user/? HTTP/1.1" 200 11916
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/user/?_facets=True HTTP/1.1" 200 12323
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6790
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 200 7499
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /admin/apphw/client/ HTTP/1.1" 200 16994
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/apphw/order/ HTTP/1.1" 200 8527
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/apphw/order/add/ HTTP/1.1" 200 14727
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/css/forms.css HTTP/1.1" 200 9090
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /admin/apphw/product/add/?_to_field=id&_popup=1 HTTP/1.1" 200 6949
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/apphw/client/6/change/?_to_field=id HTTP/1.1" 200 12215
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/apphw/order/add/ HTTP/1.1" 200 14727
"POST /admin/apphw/order/add/ HTTP/1.1" 200 14951
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/apphw/order/add/ HTTP/1.1" 302 0
"GET /admin/apphw/order/ HTTP/1.1" 200 11242
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/apphw/product/ HTTP/1.1" 200 11062
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/apphw/order/ HTTP/1.1" 200 10840
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/apphw/order/1/change/ HTTP/1.1" 200 15555
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/apphw/client/ HTTP/1.1" 200 16994
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/apphw/order/ HTTP/1.1" 200 10840
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /create_client/10 HTTP/1.1" 200 271
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4626
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4626
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4626
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4626
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 7499
"GET /admin/apphw/product/ HTTP/1.1" 200 8541
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/apphw/product/add/ HTTP/1.1" 200 11892
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/apphw/product/add/ HTTP/1.1" 302 0
"GET /admin/apphw/product/add/ HTTP/1.1" 200 12178
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/apphw/product/add/ HTTP/1.1" 302 0
"GET /admin/apphw/product/ HTTP/1.1" 200 11301
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/apphw/order/ HTTP/1.1" 200 8527
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
Internal Server Error: /admin/apphw/order/add/
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1871, in _changeform_view
    form = ModelForm(initial=initial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 363, in __init__
    self.instance = opts.model()
                    ^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 535, in __init__
    val = field.get_default()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1021, in get_default
    return self._get_default()
           ^^^^^^^^^^^^^^^^^^^
TypeError: Order.get_sum() missing 1 required positional argument: 'self'
"GET /admin/apphw/order/add/ HTTP/1.1" 500 136557
"GET /admin/apphw/order/ HTTP/1.1" 200 8527
Internal Server Error: /admin/apphw/order/add/
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1871, in _changeform_view
    form = ModelForm(initial=initial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 363, in __init__
    self.instance = opts.model()
                    ^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 535, in __init__
    val = field.get_default()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1021, in get_default
    return self._get_default()
           ^^^^^^^^^^^^^^^^^^^
TypeError: Order.get_sum() missing 1 required positional argument: 'self'
"GET /admin/apphw/order/add/ HTTP/1.1" 500 136557
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /admin/apphw/order/add/
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1871, in _changeform_view
    form = ModelForm(initial=initial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 363, in __init__
    self.instance = opts.model()
                    ^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 535, in __init__
    val = field.get_default()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1021, in get_default
    return self._get_default()
           ^^^^^^^^^^^^^^^^^^^
TypeError: Order.get_sum() missing 1 required positional argument: 'self'
"GET /admin/apphw/order/add/ HTTP/1.1" 500 136525
"GET /admin/apphw/order/ HTTP/1.1" 200 8527
Internal Server Error: /admin/apphw/order/add/
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1871, in _changeform_view
    form = ModelForm(initial=initial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 363, in __init__
    self.instance = opts.model()
                    ^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 535, in __init__
    val = field.get_default()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1021, in get_default
    return self._get_default()
           ^^^^^^^^^^^^^^^^^^^
TypeError: Order.get_sum() missing 1 required positional argument: 'self'
"GET /admin/apphw/order/add/ HTTP/1.1" 500 136557
"GET /admin/apphw/order/ HTTP/1.1" 200 8527
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/apphw/order/ HTTP/1.1" 200 8527
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
Internal Server Error: /admin/apphw/order/add/
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\contrib\admin\options.py", line 1871, in _changeform_view
    form = ModelForm(initial=initial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\forms\models.py", line 363, in __init__
    self.instance = opts.model()
                    ^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\base.py", line 535, in __init__
    val = field.get_default()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Django\django_venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1021, in get_default
    return self._get_default()
           ^^^^^^^^^^^^^^^^^^^
TypeError: Order.get_sum() missing 1 required positional argument: 'self'
"GET /admin/apphw/order/add/ HTTP/1.1" 500 136557
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Django\HW\HW_proj\apphw\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 691
Not Found: /input_image
"GET /input_image HTTP/1.1" 404 3679
"GET /create_client/10 HTTP/1.1" 200 271
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 7499
"GET /admin/apphw/order/ HTTP/1.1" 200 8527
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/apphw/client/ HTTP/1.1" 200 16946
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
